import React, { useState, useEffect } from 'react'
import { ArrowRight, BookOpen, Zap, Globe, Shield, TrendingUp, Search, ChevronRight, ExternalLink } from 'lucide-react'

interface LandingProps {
  onLaunch: () => void
}

function useDarkMode() {
  const [dark, setDark] = useState(() => {
    if (typeof window === 'undefined') return false
    return (
      document.documentElement.classList.contains('dark') ||
      localStorage.getItem('theme') === 'dark'
    )
  })
  useEffect(() => {
    if (dark) {
      document.documentElement.classList.add('dark')
      localStorage.setItem('theme', 'dark')
    } else {
      document.documentElement.classList.remove('dark')
      localStorage.setItem('theme', 'light')
    }
  }, [dark])
  return [dark, setDark] as const
}

const FEATURES = [
  {
    icon: Zap,
    title: 'Autonomous Agent',
    desc: 'Runs on Ritual Chain compute — no server, no human in the loop. Wakes up every cycle, scores papers, publishes on-chain.',
    color: 'text-yellow-500',
    bg: 'bg-yellow-50 dark:bg-yellow-900/20',
  },
  {
    icon: BookOpen,
    title: 'Multi-Source Search',
    desc: 'Search across arXiv, Semantic Scholar, PubMed, and CrossRef simultaneously. Results ranked by relevance and recency.',
    color: 'text-blue-500',
    bg: 'bg-blue-50 dark:bg-blue-900/20',
  },
  {
    icon: TrendingUp,
    title: 'Relevance Scoring',
    desc: 'On-chain ML scores each paper for relevance to ML, CV, NLP, and RL. High ≥85% · Medium ≥65% · Low <65%.',
    color: 'text-green-500',
    bg: 'bg-green-50 dark:bg-green-900/20',
  },
  {
    icon: Shield,
    title: 'On-Chain Subscription',
    desc: 'Subscribe with RITUAL tokens via a transparent smart contract. No emails, no accounts — just your wallet.',
    color: 'text-purple-500',
    bg: 'bg-purple-50 dark:bg-purple-900/20',
  },
  {
    icon: Globe,
    title: 'Live Event Updates',
    desc: 'Feed auto-refreshes when a new DigestPublished event fires on-chain. Always showing the latest cycle.',
    color: 'text-cyan-500',
    bg: 'bg-cyan-50 dark:bg-cyan-900/20',
  },
  {
    icon: Search,
    title: 'AI Summaries',
    desc: 'Every paper card includes a one-line AI key insight — hover to read the full summary generated by the agent.',
    color: 'text-pink-500',
    bg: 'bg-pink-50 dark:bg-pink-900/20',
  },
]

const STEPS = [
  {
    num: '01',
    icon: '⏰',
    title: 'Agent wakes up on Ritual Chain',
    desc: "Every scheduled block, the DigestAgent smart contract is invoked automatically via Ritual's keeper network.",
  },
  {
    num: '02',
    icon: '📚',
    title: 'Fetches & scores latest papers',
    desc: 'Pulls the newest ML, CV, NLP, and RL papers from arXiv. An on-chain ML model scores each paper for relevance.',
  },
  {
    num: '03',
    icon: '📡',
    title: 'Publishes digest on-chain',
    desc: 'Top-scored papers are written to the contract and a DigestPublished event fires. Subscribers receive the cycle.',
  },
]

const MOCK_CARD = {
  title: 'Scaling Language Models: Methods, Analysis & Insights',
  topic: 'NLP',
  score: '94% match',
  aiSummary: 'Key insight: scaling alone produces qualitative capability jumps. Gopher outperforms GPT-3 on 100+ tasks while revealing where pure scale hits diminishing returns.',
  tags: ['#scaling', '#language-models', '#nlp'],
  citations: '3,812 citations',
}

export default function Landing({ onLaunch }: LandingProps) {
  const [dark, setDark] = useDarkMode()
  const [hoverCard, setHoverCard] = useState(false)

  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-white overflow-x-hidden">

      {/* Nav */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/80 dark:bg-slate-950/80 backdrop-blur border-b border-slate-200 dark:border-slate-800">
        <div className="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-blue-600 flex items-center justify-center">
              <span className="text-white text-xs font-bold">RF</span>
            </div>
            <span className="text-lg font-bold tracking-tight">RitualFeed</span>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={() => setDark(!dark)}
              className="p-1.5 rounded-lg text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors text-sm"
              aria-label="Toggle dark mode"
            >
              {dark ? '☀️' : '🌙'}
            </button>
            <a
              href="https://explorer.ritualfoundation.org"
              target="_blank"
              rel="noopener noreferrer"
              className="hidden sm:inline-flex items-center gap-1 text-sm text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
            >
              Explorer <ExternalLink className="w-3 h-3" />
            </a>
            <button
              onClick={onLaunch}
              className="inline-flex items-center gap-1.5 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium px-4 py-1.5 rounded-lg transition-colors"
            >
              Launch App <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative pt-32 pb-20 px-6 overflow-hidden">
        {/* Background glow */}
        <div className="absolute inset-0 pointer-events-none overflow-hidden">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[900px] h-[500px] rounded-full bg-blue-600/10 dark:bg-blue-600/20 blur-3xl" />
          <div className="absolute top-20 left-1/4 w-[400px] h-[300px] rounded-full bg-purple-600/8 dark:bg-purple-600/15 blur-3xl" />
          <div className="absolute top-10 right-1/4 w-[350px] h-[250px] rounded-full bg-cyan-500/8 dark:bg-cyan-500/12 blur-3xl" />
        </div>

        <div className="max-w-4xl mx-auto text-center relative">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-800 text-blue-700 dark:text-blue-300 text-xs font-medium mb-6">
            <span className="relative flex h-1.5 w-1.5">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75" />
              <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-blue-500" />
            </span>
            Live on Ritual Testnet · Chain ID 1979
          </div>

          <h1 className="text-5xl sm:text-6xl font-extrabold tracking-tight leading-[1.1]">
            Your AI Research Agent,{' '}
            <span className="bg-gradient-to-r from-blue-600 via-purple-600 to-cyan-500 bg-clip-text text-transparent">
              Live on Ritual Chain
            </span>
          </h1>

          <p className="mt-6 text-lg sm:text-xl text-slate-500 dark:text-slate-400 max-w-2xl mx-auto leading-relaxed">
            An autonomous on-chain agent fetches the latest AI research papers,
            scores them with on-chain ML, and publishes a daily digest — no server, no middleman.
          </p>

          <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
            <button
              onClick={onLaunch}
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white font-semibold px-8 py-3.5 rounded-xl transition-all duration-200 shadow-lg shadow-blue-600/25 hover:shadow-blue-600/40 text-base"
            >
              Launch the Feed
              <ArrowRight className="w-4 h-4" />
            </button>
            <a
              href="https://explorer.ritualfoundation.org"
              target="_blank"
              rel="noopener noreferrer"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 font-medium px-8 py-3.5 rounded-xl transition-colors text-base"
            >
              View on Explorer
              <ExternalLink className="w-4 h-4" />
            </a>
          </div>

          {/* Stats */}
          <div className="mt-14 grid grid-cols-3 gap-6 max-w-lg mx-auto">
            {[
              { value: '4', label: 'Sources searched' },
              { value: '42', label: 'Agent cycles run' },
              { value: '98%', label: 'Success rate' },
            ].map(({ value, label }) => (
              <div key={label} className="text-center">
                <p className="text-3xl font-bold text-slate-900 dark:text-white">{value}</p>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Live Paper Card Preview */}
      <section className="py-12 px-6 bg-slate-50 dark:bg-slate-900/50 border-y border-slate-200 dark:border-slate-800">
        <div className="max-w-4xl mx-auto">
          <p className="text-center text-xs font-semibold text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-8">
            What a digest looks like
          </p>
          <div className="flex justify-center">
            <div
              className={`relative bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-6 max-w-md w-full shadow-sm transition-all duration-300 cursor-default ${hoverCard ? 'shadow-lg border-blue-300 dark:border-blue-700' : ''}`}
              onMouseEnter={() => setHoverCard(true)}
              onMouseLeave={() => setHoverCard(false)}
            >
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-medium px-2.5 py-1 rounded-full" style={{ background: '#EDE9FE', color: '#5B21B6' }}>
                  {MOCK_CARD.topic}
                </span>
                <span className="text-xs font-semibold px-2.5 py-1 rounded-md border" style={{ background: '#D1FAE5', color: '#065F46', borderColor: '#6EE7B7' }}>
                  🎯 {MOCK_CARD.score}
                </span>
              </div>
              <h3 className="font-semibold text-slate-900 dark:text-white leading-snug">{MOCK_CARD.title}</h3>
              <p className="mt-1.5 text-xs text-slate-500 dark:text-slate-400">Authors: Jack W. Rae, Sebastian Borgeaud et al.</p>

              <div className={`mt-3 p-2.5 rounded-md bg-blue-50 dark:bg-blue-900/20 border-l-2 border-blue-400 transition-all duration-200 ${hoverCard ? '' : ''}`}>
                <p className="text-xs font-medium text-blue-800 dark:text-blue-300 mb-1 flex items-center gap-1">
                  ✨ AI Summary
                  {!hoverCard && <span className="text-blue-400 text-[10px] font-normal">— hover to expand</span>}
                </p>
                <p className={`text-xs text-blue-700 dark:text-blue-400 leading-relaxed transition-all duration-200 ${hoverCard ? '' : 'line-clamp-1'}`}>
                  {MOCK_CARD.aiSummary}
                </p>
              </div>

              <div className="mt-3 flex flex-wrap gap-1.5">
                {MOCK_CARD.tags.map(t => (
                  <span key={t} className="px-2 py-0.5 rounded-full bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 text-xs font-medium">{t}</span>
                ))}
              </div>
              <p className="mt-2 text-xs text-slate-400">📚 {MOCK_CARD.citations}</p>
              <div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-700 flex items-center justify-between">
                <span className="text-xs text-slate-400">12 min ago</span>
                <span className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-md bg-blue-500 text-white text-xs font-medium">
                  arXiv <ExternalLink className="w-3 h-3" />
                </span>
              </div>

              {/* Hover label */}
              {hoverCard && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-blue-600 text-white text-[10px] font-semibold px-2.5 py-1 rounded-full whitespace-nowrap">
                  ← AI Summary expanded!
                </div>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold">How it works</h2>
            <p className="mt-3 text-slate-500 dark:text-slate-400 max-w-xl mx-auto">
              Fully autonomous — no humans, no cron jobs, no centralised servers.
            </p>
          </div>

          <div className="relative">
            {/* Connector line */}
            <div className="hidden md:block absolute top-12 left-[calc(16.67%+24px)] right-[calc(16.67%+24px)] h-px bg-gradient-to-r from-blue-200 via-purple-200 to-cyan-200 dark:from-blue-800 dark:via-purple-800 dark:to-cyan-800" />

            <div className="grid md:grid-cols-3 gap-8">
              {STEPS.map((step, i) => (
                <div key={step.num} className="relative flex flex-col items-center text-center">
                  <div className={`w-14 h-14 rounded-2xl flex items-center justify-center text-2xl mb-4 ${
                    i === 0 ? 'bg-blue-100 dark:bg-blue-900/40' :
                    i === 1 ? 'bg-purple-100 dark:bg-purple-900/40' :
                    'bg-cyan-100 dark:bg-cyan-900/40'
                  }`}>
                    {step.icon}
                  </div>
                  <p className={`text-xs font-bold mb-1 ${
                    i === 0 ? 'text-blue-500' : i === 1 ? 'text-purple-500' : 'text-cyan-500'
                  }`}>
                    STEP {step.num}
                  </p>
                  <h3 className="text-base font-semibold text-slate-900 dark:text-white mb-2 leading-snug">
                    {step.title}
                  </h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
                    {step.desc}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Features grid */}
      <section className="py-20 px-6 bg-slate-50 dark:bg-slate-900/50 border-y border-slate-200 dark:border-slate-800">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold">Everything you need</h2>
            <p className="mt-3 text-slate-500 dark:text-slate-400">
              Built for researchers who want signal, not noise.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {FEATURES.map(({ icon: Icon, title, desc, color, bg }) => (
              <div
                key={title}
                className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl p-5 hover:border-blue-300 dark:hover:border-blue-700 hover:shadow-sm transition-all duration-200"
              >
                <div className={`w-10 h-10 rounded-xl ${bg} flex items-center justify-center mb-4`}>
                  <Icon className={`w-5 h-5 ${color}`} />
                </div>
                <h3 className="text-sm font-semibold text-slate-900 dark:text-white mb-1.5">{title}</h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA section */}
      <section className="py-24 px-6 relative overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[700px] h-[300px] rounded-full bg-blue-600/8 dark:bg-blue-600/15 blur-3xl" />
        </div>
        <div className="max-w-2xl mx-auto text-center relative">
          <div className="text-5xl mb-6">🔬</div>
          <h2 className="text-3xl sm:text-4xl font-bold leading-snug">
            Stay ahead of the research curve.
          </h2>
          <p className="mt-4 text-slate-500 dark:text-slate-400 text-lg leading-relaxed">
            Connect your wallet, subscribe for RITUAL tokens, and get every digest as it's published on-chain.
          </p>
          <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
            <button
              onClick={onLaunch}
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold px-8 py-3.5 rounded-xl transition-all duration-200 shadow-lg shadow-blue-600/25 text-base"
            >
              Launch Feed
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
          <p className="mt-5 text-xs text-slate-400 dark:text-slate-500">
            No account required · Wallet connect only · Ritual Testnet
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-200 dark:border-slate-800 py-8 px-6">
        <div className="max-w-4xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 rounded bg-blue-600 flex items-center justify-center">
              <span className="text-white text-[9px] font-bold">RF</span>
            </div>
            <span className="text-sm font-semibold text-slate-900 dark:text-white">RitualFeed</span>
            <span className="text-xs text-slate-400">· Powered by Ritual Chain</span>
          </div>
          <div className="flex items-center gap-5 text-xs text-slate-400">
            <a href="https://ritual.net" target="_blank" rel="noopener noreferrer" className="hover:text-slate-600 dark:hover:text-slate-300 transition-colors">Ritual</a>
            <a href="https://arxiv.org" target="_blank" rel="noopener noreferrer" className="hover:text-slate-600 dark:hover:text-slate-300 transition-colors">arXiv</a>
            <a href="https://explorer.ritualfoundation.org" target="_blank" rel="noopener noreferrer" className="hover:text-slate-600 dark:hover:text-slate-300 transition-colors">Explorer</a>
            <button
              onClick={onLaunch}
              className="hover:text-slate-600 dark:hover:text-slate-300 transition-colors"
            >
              Launch App →
            </button>
          </div>
        </div>
      </footer>
    </div>
  )
}
